define([
  
    // All the blocks...
    "../blockly/blocks/lists",
    "../blockly/blocks/logic",
    "../blockly/blocks/loops",
    "../blockly/blocks/math",
    "../blockly/blocks/procedures",
    "../blockly/blocks/robActions",
    "../blockly/blocks/robBrick",
    "../blockly/blocks/robColour",
    "../blockly/blocks/robCommunication",
    "../blockly/blocks/robControls",
    "../blockly/blocks/robSensors",
    "../blockly/blocks/simActions",
    "../blockly/blocks/simSensors",
    "../blockly/blocks/text",
    "../blockly/blocks/unityControls",
    "../blockly/blocks/unityEvents",
    "../blockly/blocks/unitySendMessages",
    "../blockly/blocks/unityRaycast",
    "../blockly/blocks/unityGeneral",
    "../blockly/blocks/unityInput",
    "../blockly/blocks/unityMove",
    "../blockly/blocks/unityRender",
    "../blockly/blocks/unityRotate",
    "../blockly/blocks/unityTime",
    "../blockly/blocks/unityVector",
    "../blockly/blocks/unityObjects",
    "../blockly/blocks/unityDetect",
    "../blockly/blocks/unityCode",
    "../blockly/blocks/variables",
  
    // The code generation
    "../blockly/generators/csharp",
    //"../blockly/generators/csharp/lists",
    "../blockly/generators/csharp/logic",
    //"../blockly/generators/csharp/loops",
    "../blockly/generators/csharp/math",
    "../blockly/generators/csharp/text",
    //"../blockly/generators/csharp/variables",
    "../blockly/generators/csharp/unityControls",
    "../blockly/generators/csharp/unityEvents",
    "../blockly/generators/csharp/unitySendMessages",
    "../blockly/generators/csharp/unityRaycast",
    "../blockly/generators/csharp/unityGeneral",
    "../blockly/generators/csharp/unityInput",
    "../blockly/generators/csharp/unityMove",
    "../blockly/generators/csharp/unityRender",
    "../blockly/generators/csharp/unityRotate",
    "../blockly/generators/csharp/unityTime",
    "../blockly/generators/csharp/unityVector",
    "../blockly/generators/csharp/unityObjects",
    "../blockly/generators/csharp/unityDetect",
    "../blockly/generators/csharp/unityCode",
    "../blockly/generators/csharp/variables",
    ], function(){
    // When developing, this file loads all the blocks by using the non-optimized files
    // That way you can get immediate feedback about whether a block works or not
    
    // Note that in a build, this file is not used
});