// This file was automatically generated.  Do not modify.

'use strict';

goog.provide('Blockly.Msg.tl');

goog.require('Blockly.Msg');

Blockly.Msg.ADD_COMMENT = "Dagdag komento";
Blockly.Msg.AUTH = "Please authorize this app to enable your work to be saved and to allow it to be shared by you.";  // untranslated
Blockly.Msg.CHANGE_VALUE_TITLE = "pagbago ng value:";
Blockly.Msg.CHAT = "Chat with your collaborator by typing in this box!";  // untranslated
Blockly.Msg.CLEAN_UP = "Clean up Blocks";  // untranslated
Blockly.Msg.COLLAPSE_ALL = "bloke";
Blockly.Msg.COLLAPSE_BLOCK = "bloke";
Blockly.Msg.COLOUR_BLEND_COLOUR1 = "kulay 1";
Blockly.Msg.COLOUR_BLEND_COLOUR2 = "kulay 2";
Blockly.Msg.COLOUR_BLEND_HELPURL = "http://meyerweb.com/eric/tools/color-blend/";
Blockly.Msg.COLOUR_BLEND_RATIO = "proporsyon";
Blockly.Msg.COLOUR_BLEND_TITLE = "halo";
Blockly.Msg.COLOUR_BLEND_TOOLTIP = "Paghalo ng dalawang kulay kasama ng ibinigay na proporsyon (0.0 - 1.0).";
Blockly.Msg.COLOUR_PICKER_HELPURL = "http://en.wikipedia.org/wiki/Color";
Blockly.Msg.COLOUR_PICKER_TOOLTIP = "pagpili ng kulay sa paleta.";
Blockly.Msg.COLOUR_RANDOM_HELPURL = "http://randomcolour.com";  // untranslated
Blockly.Msg.COLOUR_RANDOM_TITLE = "iba ibang kulay";
Blockly.Msg.COLOUR_RANDOM_TOOLTIP = "pagpili ng iba't ibang kulay.";
Blockly.Msg.COLOUR_RGB_BLUE = "asul";
Blockly.Msg.COLOUR_RGB_GREEN = "berde";
Blockly.Msg.COLOUR_RGB_HELPURL = "http://www.december.com/html/spec/colorper.html";
Blockly.Msg.COLOUR_RGB_RED = "pula";
Blockly.Msg.COLOUR_RGB_TITLE = "kulayan ng";
Blockly.Msg.CONTROLS_FLOW_STATEMENTS_HELPURL = "https://github.com/google/blockly/wiki/Loops#loop-termination-blocks";  // untranslated
Blockly.Msg.CONTROLS_FLOW_STATEMENTS_OPERATOR_BREAK = "putulin ang paulit ulit";
Blockly.Msg.CONTROLS_FLOW_STATEMENTS_OPERATOR_CONTINUE = "Magpatuloy sa susunod na pag-ulit ng loop";
Blockly.Msg.CONTROLS_FLOW_STATEMENTS_TOOLTIP_BREAK = "Hatiin ang nilalaman ng loop.";
Blockly.Msg.CONTROLS_FLOW_STATEMENTS_TOOLTIP_CONTINUE = "Laktawan ang natitirang bahagi ng loop, at magpatuloy sa susunod na pag-ulit.";
Blockly.Msg.CONTROLS_FLOW_STATEMENTS_WARNING = "Babala: Ang block ito ay maaari lamang magamit sa loob ng loop.";
Blockly.Msg.CONTROLS_FOREACH_HELPURL = "https://github.com/google/blockly/wiki/Loops#for-each";  // untranslated
Blockly.Msg.CONTROLS_FOREACH_TITLE = "sa bawat bagay %1 sa listahan %2";
Blockly.Msg.CONTROLS_FOREACH_TOOLTIP = "Para sa bawat item sa isang list, i-set ang variable ng '%1' sa mga item, at pagkatapos ay gumawa ng ilang mga statements.";
Blockly.Msg.CONTROLS_FOR_HELPURL = "https://github.com/google/blockly/wiki/Loops#count-with";  // untranslated
Blockly.Msg.CONTROLS_FOR_TITLE = "bilangin %1 mula %2 hanggang %3 ng %4";
Blockly.Msg.CONTROLS_FOR_TOOLTIP = "Magkaroon ng mga variable na \"%1\" na tanggalin ng mga halaga mula sa simulang numero hanggang sa dulong numero, at bilangin sa pamamagitan ng tinukoy na agwat, at gawin ang mga tinukoy na mga blocks.";
Blockly.Msg.CONTROLS_IF_ELSEIF_TOOLTIP = "Mag dagdag ng condition sa if block.";
Blockly.Msg.CONTROLS_IF_ELSE_TOOLTIP = "Mag Add ng final, kunin lahat ng condition sa if block.";
Blockly.Msg.CONTROLS_IF_HELPURL = "https://github.com/google/blockly/wiki/IfElse";  // untranslated
Blockly.Msg.CONTROLS_IF_IF_TOOLTIP = "Mag Add, remove o kaya mag reorder ng sections para maayos ang if block.";
Blockly.Msg.CONTROLS_IF_MSG_ELSE = "else";
Blockly.Msg.CONTROLS_IF_MSG_ELSEIF = "else if";
Blockly.Msg.CONTROLS_IF_MSG_IF = "kung";
Blockly.Msg.CONTROLS_IF_TOOLTIP_1 = "kung ang value ay true,  gagawin ang do statements.";
Blockly.Msg.CONTROLS_IF_TOOLTIP_2 = "Kung ang value ay true, gagawin ang unang block ng do statements. Kung hindi, gagawin ang pangalawang block ng statement.";
Blockly.Msg.CONTROLS_IF_TOOLTIP_3 = "Kung ang unang value ay true, gagawin ang first block ng statement. Kung hindi, kung ang second value ay true, gagawin ang second block ng statement.";
Blockly.Msg.CONTROLS_IF_TOOLTIP_4 = "Kung ang first value ay true, gagawin ang first block ng statement. Kung hindi true ang second value, gagawin ang second block ng statement. Kung wala sa mga values ay true, gagawin ang last block ng statements.";
Blockly.Msg.CONTROLS_REPEAT_HELPURL = "http://en.wikipedia.org/wiki/For_loop";
Blockly.Msg.CONTROLS_REPEAT_INPUT_DO = "gawin";
Blockly.Msg.CONTROLS_REPEAT_TITLE = "ulitin %1 beses";
Blockly.Msg.CONTROLS_REPEAT_TOOLTIP = "gumawa ng ilang pangungusap ng ilang ulit.";
Blockly.Msg.CONTROLS_WHILEUNTIL_HELPURL = "https://github.com/google/blockly/wiki/Loops#repeat";  // untranslated
Blockly.Msg.CONTROLS_WHILEUNTIL_OPERATOR_UNTIL = "ulitin hanggang";
Blockly.Msg.CONTROLS_WHILEUNTIL_OPERATOR_WHILE = "ulitin habang";
Blockly.Msg.CONTROLS_WHILEUNTIL_TOOLTIP_UNTIL = "Habang ang value ay false, gagawin ang ibang statements.";
Blockly.Msg.CONTROLS_WHILEUNTIL_TOOLTIP_WHILE = "Habang ang value ay true, gagawin ang ibang statements.";
Blockly.Msg.DELETE_ALL_BLOCKS = "Delete all %1 blocks?";  // untranslated
Blockly.Msg.DELETE_BLOCK = "burahin ang bloke";
Blockly.Msg.DELETE_X_BLOCKS = "burahin %1 ng bloke";
Blockly.Msg.DEPRECATEDBLOCK = "This block is outdated and will be removed from Vubbi.";  // untranslated
Blockly.Msg.DISABLE_BLOCK = "Ipangwalang bisa ang Block";
Blockly.Msg.DUPLICATE_BLOCK = "Kaparehas";
Blockly.Msg.ENABLE_BLOCK = "Bigyan ng bisa ang Block";
Blockly.Msg.EXPAND_ALL = "Palawakin ang Blocks";
Blockly.Msg.EXPAND_BLOCK = "Palawakin ang Block";
Blockly.Msg.EXTERNAL_INPUTS = "Panlabas na Inputs";
Blockly.Msg.HELP = "Tulong";
Blockly.Msg.INLINE_INPUTS = "Inline na Inputs";
Blockly.Msg.LISTS_CREATE_EMPTY_HELPURL = "https://github.com/google/blockly/wiki/Lists#create-empty-list";
Blockly.Msg.LISTS_CREATE_EMPTY_TITLE = "Gumawa ng walang laman na list";
Blockly.Msg.LISTS_CREATE_EMPTY_TOOLTIP = "Ibabalik ang list, na may haba na 0, nag lalaman ng walang data records";
Blockly.Msg.LISTS_CREATE_WITH_CONTAINER_TITLE_ADD = "list";
Blockly.Msg.LISTS_CREATE_WITH_CONTAINER_TOOLTIP = "Magdagdag, mag tanggal or mag ayos ng sections para muling maayos ang listahan ng block.";
Blockly.Msg.LISTS_CREATE_WITH_HELPURL = "https://github.com/google/blockly/wiki/Lists#create-list-with";  // untranslated
Blockly.Msg.LISTS_CREATE_WITH_INPUT_WITH = "gumawa ng list kasama";
Blockly.Msg.LISTS_CREATE_WITH_ITEM_TOOLTIP = "Mag dagdag ng item sa list.";
Blockly.Msg.LISTS_CREATE_WITH_TOOLTIP = "Gumawa ng list na may kahit anong number ng items.";
Blockly.Msg.LISTS_GET_INDEX_FIRST = "Una";
Blockly.Msg.LISTS_GET_INDEX_FROM_END = "# mula katapusan";
Blockly.Msg.LISTS_GET_INDEX_FROM_START = "#";
Blockly.Msg.LISTS_GET_INDEX_GET = "kunin";
Blockly.Msg.LISTS_GET_INDEX_GET_REMOVE = "kunin at tanggalin";
Blockly.Msg.LISTS_GET_INDEX_LAST = "huli";
Blockly.Msg.LISTS_GET_INDEX_RANDOM = "nang hindi pinipili";
Blockly.Msg.LISTS_GET_INDEX_REMOVE = "tanggalin";
Blockly.Msg.LISTS_GET_INDEX_TAIL = "";  // untranslated
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_FIRST = "Ibalik ang unang item sa list.";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_FROM_END = "Ibalik ang item sa tinakdang posisyon sa list. #1 ay ang huling item.";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_FROM_START = "Ibalik ang item sa itinakdang posisyon sa list. #1 ay ang unang item.";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_LAST = "Ibalik ang huling item sa list.";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_RANDOM = "Nag babalik ng hindi pinipiling item sa list.";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_REMOVE_FIRST = "Nag tatanggal at nag babalik ng mga unang item sa list.";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_REMOVE_FROM_END = "Nag tatanggal at nag babalik ng items sa tinukoy na posisyon sa list. #1 ay ang huling item.";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_REMOVE_FROM_START = "Nag tatanggal at nag babalik ng mga items sa tinukoy na posisyon sa list. #1 ang unang item.";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_REMOVE_LAST = "Nag tatanggal at nag babalik ng huling item sa list.";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_REMOVE_RANDOM = "Nag tatanggal at nag babalik ng mga hindi pinipiling item sa list.";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_REMOVE_FIRST = "Nag tatanggal ng unang item sa list.";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_REMOVE_FROM_END = "Nag tatanggal ng item sa tinukoy na posisyon sa list. #1 ay ang huling item.";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_REMOVE_FROM_START = "Nag tatanggal ng item sa tinukoy na posisyon sa list. #1 ay ang unang item.";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_REMOVE_LAST = "Nag tatanggal ng huling item sa list.";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_REMOVE_RANDOM = "Nag tatanggal ng item mula sa walang pinipiling list.";
Blockly.Msg.LISTS_GET_SUBLIST_END_FROM_END = "mula # hanggang huli";
Blockly.Msg.LISTS_GET_SUBLIST_END_FROM_START = "mula #";
Blockly.Msg.LISTS_GET_SUBLIST_END_LAST = "hanggang huli";
Blockly.Msg.LISTS_GET_SUBLIST_HELPURL = "https://github.com/google/blockly/wiki/Lists#getting-a-sublist";  // untranslated
Blockly.Msg.LISTS_GET_SUBLIST_START_FIRST = "pag kuha ng sub-list mula sa una";
Blockly.Msg.LISTS_GET_SUBLIST_START_FROM_END = "pag kuha ng sub-list mula sa # mula huli";
Blockly.Msg.LISTS_GET_SUBLIST_START_FROM_START = "pag kuha ng sub-list mula #";
Blockly.Msg.LISTS_GET_SUBLIST_TAIL = "";  // untranslated
Blockly.Msg.LISTS_GET_SUBLIST_TOOLTIP = "Gumagawa ng kopya ng tinukoy na bahagi ng list.";
Blockly.Msg.LISTS_INDEX_OF_FIRST = "Hanapin ang unang pangyayari ng item";
Blockly.Msg.LISTS_INDEX_OF_HELPURL = "https://github.com/google/blockly/wiki/Lists#getting-items-from-a-list";  // untranslated
Blockly.Msg.LISTS_INDEX_OF_LAST = "hanapin ang huling pangyayari ng item";
Blockly.Msg.LISTS_INDEX_OF_TOOLTIP = "Pagbalik ng index ng una/huli pangyayari ng item sa list. Pagbalik ng 0 kung ang item ay hindi makita.";
Blockly.Msg.LISTS_INLIST = "sa list";
Blockly.Msg.LISTS_ISEMPTY_HELPURL = "https://github.com/google/blockly/wiki/Lists#is-empty";  // untranslated
Blockly.Msg.LISTS_ISEMPTY_TITLE = "%1 ay walang laman";
Blockly.Msg.LISTS_ISEMPTY_TOOLTIP = "Nagbabalik ng true kung ang list ay walang laman.";
Blockly.Msg.LISTS_LENGTH_HELPURL = "https://github.com/google/blockly/wiki/Lists#length-of";  // untranslated
Blockly.Msg.LISTS_LENGTH_TITLE = "haba ng %1";
Blockly.Msg.LISTS_LENGTH_TOOLTIP = "Pag balik ng haba ng list.";
Blockly.Msg.LISTS_REPEAT_HELPURL = "https://github.com/google/blockly/wiki/Lists#create-list-with";  // untranslated
Blockly.Msg.LISTS_REPEAT_TITLE = "pag gawa ng list kasama ng item %1 inuulit %2 beses";
Blockly.Msg.LISTS_REPEAT_TOOLTIP = "Pag gawa ng list na binubuo ng binigay na value at inulit na tinuloy na bilang ng beses.";
Blockly.Msg.LISTS_SET_INDEX_HELPURL = "https://github.com/google/blockly/wiki/Lists#in-list--set";  // untranslated
Blockly.Msg.LISTS_SET_INDEX_INPUT_TO = "gaya ng";
Blockly.Msg.LISTS_SET_INDEX_INSERT = "isingit sa";
Blockly.Msg.LISTS_SET_INDEX_SET = "set";
Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_INSERT_FIRST = "Nag singit ng item sa simula ng list.";
Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_INSERT_FROM_END = "Nag singit ng item sa tinukoy na posisyon sa list. #1 ay ang huling item.";
Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_INSERT_FROM_START = "Nag singit ng item sa tinukoy na posistion sa list. #1 ay ang unang item.";
Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_INSERT_LAST = "Idagdag ang item sa huli ng isang list.";
Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_INSERT_RANDOM = "Isingit ang item ng walang pinipili sa isang list.";
Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_SET_FIRST = "Pag set ng unang item sa isang list.";
Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_SET_FROM_END = "Pag set ng item sa tinukoy na posisyon sa isang list. #1 ay ang huling item.";
Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_SET_FROM_START = "Pag set ng item sa tinukoy na position sa isang list. #1 ay ang unang item.";
Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_SET_LAST = "Pag set sa huling item sa isang list.";
Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_SET_RANDOM = "Pag set ng walang pinipiling item sa isang list.";
Blockly.Msg.LISTS_SORT_HELPURL = "https://github.com/google/blockly/wiki/Lists#sorting-a-list";  // untranslated
Blockly.Msg.LISTS_SORT_ORDER_ASCENDING = "ascending";  // untranslated
Blockly.Msg.LISTS_SORT_ORDER_DESCENDING = "descending";  // untranslated
Blockly.Msg.LISTS_SORT_TITLE = "sort %1 %2 %3";  // untranslated
Blockly.Msg.LISTS_SORT_TOOLTIP = "Sort a copy of a list.";  // untranslated
Blockly.Msg.LISTS_SORT_TYPE_IGNORECASE = "alphabetic, ignore case";  // untranslated
Blockly.Msg.LISTS_SORT_TYPE_NUMERIC = "numeric";  // untranslated
Blockly.Msg.LISTS_SORT_TYPE_TEXT = "alphabetic";  // untranslated
Blockly.Msg.LISTS_SPLIT_HELPURL = "https://github.com/google/blockly/wiki/Lists#splitting-strings-and-joining-lists";  // untranslated
Blockly.Msg.LISTS_SPLIT_LIST_FROM_TEXT = "make list from text";  // untranslated
Blockly.Msg.LISTS_SPLIT_TEXT_FROM_LIST = "make text from list";  // untranslated
Blockly.Msg.LISTS_SPLIT_TOOLTIP_JOIN = "Join a list of texts into one text, separated by a delimiter.";  // untranslated
Blockly.Msg.LISTS_SPLIT_TOOLTIP_SPLIT = "Split text into a list of texts, breaking at each delimiter.";  // untranslated
Blockly.Msg.LISTS_SPLIT_WITH_DELIMITER = "with delimiter";  // untranslated
Blockly.Msg.LOGIC_BOOLEAN_FALSE = "mali";
Blockly.Msg.LOGIC_BOOLEAN_HELPURL = "https://github.com/google/blockly/wiki/Logic#values";  // untranslated
Blockly.Msg.LOGIC_BOOLEAN_TOOLTIP = "Nag babalik ng true or false.";
Blockly.Msg.LOGIC_BOOLEAN_TRUE = "tama";
Blockly.Msg.LOGIC_COMPARE_HELPURL = "http://en.wikipedia.org/wiki/Inequality_(mathematics)";
Blockly.Msg.LOGIC_COMPARE_TOOLTIP_EQ = "Nag babalik ng true kung ang pinasok ay parehong magkatumbas.";
Blockly.Msg.LOGIC_COMPARE_TOOLTIP_GT = "Nagbabalik ng true kung ang unang pinasok ay mas malaki kaysa pangalawang pinasok.";
Blockly.Msg.LOGIC_COMPARE_TOOLTIP_GTE = "Nag babalik ng true kung ang unang pinasok ay mas malaki or katumbas ng pangalawang pinasok.";
Blockly.Msg.LOGIC_COMPARE_TOOLTIP_LT = "Nag babalik ng true kung ang unang pinasok ay maliit kaysa sa pangalawang pinasok.";
Blockly.Msg.LOGIC_COMPARE_TOOLTIP_LTE = "Nag babalik ng true kung ang unang pinasok ay maliit sa o katumbas sa pangalawang pinasok.";
Blockly.Msg.LOGIC_COMPARE_TOOLTIP_NEQ = "Return true if both inputs are not equal to each other.";
Blockly.Msg.LOGIC_NEGATE_HELPURL = "https://github.com/google/blockly/wiki/Logic#not";  // untranslated
Blockly.Msg.LOGIC_NEGATE_TITLE = "not %1";
Blockly.Msg.LOGIC_NEGATE_TOOLTIP = "Returns true if the input is false.  Returns false if the input is true.";
Blockly.Msg.LOGIC_NULL = "blangko";
Blockly.Msg.LOGIC_NULL_HELPURL = "http://en.wikipedia.org/wiki/Nullable_type";
Blockly.Msg.LOGIC_NULL_TOOLTIP = "Returns null.";
Blockly.Msg.LOGIC_OPERATION_AND = "at";
Blockly.Msg.LOGIC_OPERATION_HELPURL = "https://github.com/google/blockly/wiki/Logic#logical-operations";  // untranslated
Blockly.Msg.LOGIC_OPERATION_OR = "o";
Blockly.Msg.LOGIC_OPERATION_TOOLTIP_AND = "Return true if both inputs are true.";
Blockly.Msg.LOGIC_OPERATION_TOOLTIP_OR = "Return true if at least one of the inputs is true.";
Blockly.Msg.LOGIC_TERNARY_CONDITION = "test";
Blockly.Msg.LOGIC_TERNARY_HELPURL = "http://en.wikipedia.org/wiki/%3F:";
Blockly.Msg.LOGIC_TERNARY_IF_FALSE = "kung mali";
Blockly.Msg.LOGIC_TERNARY_IF_TRUE = "kung tama";
Blockly.Msg.LOGIC_TERNARY_TOOLTIP = "Check the condition in 'test'. If the condition is true, returns the 'if true' value; otherwise returns the 'if false' value.";
Blockly.Msg.MATH_ADDITION_SYMBOL = "+";
Blockly.Msg.MATH_ARITHMETIC_HELPURL = "http://en.wikipedia.org/wiki/Arithmetic";
Blockly.Msg.MATH_ARITHMETIC_TOOLTIP_ADD = "Return the sum of the two numbers.";
Blockly.Msg.MATH_ARITHMETIC_TOOLTIP_DIVIDE = "Return the quotient of the two numbers.";
Blockly.Msg.MATH_ARITHMETIC_TOOLTIP_MINUS = "Return the difference of the two numbers.";
Blockly.Msg.MATH_ARITHMETIC_TOOLTIP_MULTIPLY = "Return the product of the two numbers.";
Blockly.Msg.MATH_ARITHMETIC_TOOLTIP_POWER = "Return the first number raised to the power of the second number.";
Blockly.Msg.MATH_CHANGE_HELPURL = "http://en.wikipedia.org/wiki/Programming_idiom#Incrementing_a_counter";
Blockly.Msg.MATH_CHANGE_TITLE = "baguhin %1 by %2";
Blockly.Msg.MATH_CHANGE_TOOLTIP = "Add a number to variable '%1'.";
Blockly.Msg.MATH_CONSTANT_HELPURL = "http://en.wikipedia.org/wiki/Mathematical_constant";
Blockly.Msg.MATH_CONSTANT_TOOLTIP = "Return one of the common constants: π (3.141…), e (2.718…), φ (1.618…), sqrt(2) (1.414…), sqrt(½) (0.707…), or ∞ (infinity).";
Blockly.Msg.MATH_CONSTRAIN_HELPURL = "https://en.wikipedia.org/wiki/Clamping_%28graphics%29";  // untranslated
Blockly.Msg.MATH_CONSTRAIN_TITLE = "constrain %1 low %2 high %3";
Blockly.Msg.MATH_CONSTRAIN_TOOLTIP = "Constrain a number to be between the specified limits (inclusive).";
Blockly.Msg.MATH_DIVISION_SYMBOL = "÷";
Blockly.Msg.MATH_IS_DIVISIBLE_BY = "is divisible by";
Blockly.Msg.MATH_IS_EVEN = "is even";
Blockly.Msg.MATH_IS_NEGATIVE = "ay negatibo";
Blockly.Msg.MATH_IS_ODD = "is odd";
Blockly.Msg.MATH_IS_POSITIVE = "ay positibo";
Blockly.Msg.MATH_IS_PRIME = "is prime";
Blockly.Msg.MATH_IS_TOOLTIP = "Check if a number is an even, odd, prime, whole, positive, negative, or if it is divisible by certain number.  Returns true or false.";
Blockly.Msg.MATH_IS_WHOLE = "is whole";
Blockly.Msg.MATH_MODULO_HELPURL = "http://en.wikipedia.org/wiki/Modulo_operation";
Blockly.Msg.MATH_MODULO_TITLE = "remainder of %1 ÷ %2";
Blockly.Msg.MATH_MODULO_TOOLTIP = "Return the remainder from dividing the two numbers.";
Blockly.Msg.MATH_MULTIPLICATION_SYMBOL = "×";
Blockly.Msg.MATH_NUMBER_HELPURL = "http://en.wikipedia.org/wiki/Number";
Blockly.Msg.MATH_NUMBER_TOOLTIP = "A number.";
Blockly.Msg.MATH_ONLIST_HELPURL = "";  // untranslated
Blockly.Msg.MATH_ONLIST_OPERATOR_AVERAGE = "average of list";
Blockly.Msg.MATH_ONLIST_OPERATOR_MAX = "max of list";
Blockly.Msg.MATH_ONLIST_OPERATOR_MEDIAN = "median of list";
Blockly.Msg.MATH_ONLIST_OPERATOR_MIN = "min of list";
Blockly.Msg.MATH_ONLIST_OPERATOR_MODE = "modes of list";
Blockly.Msg.MATH_ONLIST_OPERATOR_RANDOM = "random item of list";
Blockly.Msg.MATH_ONLIST_OPERATOR_STD_DEV = "standard deviation of list";
Blockly.Msg.MATH_ONLIST_OPERATOR_SUM = "sum of list";
Blockly.Msg.MATH_ONLIST_TOOLTIP_AVERAGE = "Return the average (arithmetic mean) of the numeric values in the list.";
Blockly.Msg.MATH_ONLIST_TOOLTIP_MAX = "Return the largest number in the list.";
Blockly.Msg.MATH_ONLIST_TOOLTIP_MEDIAN = "Return the median number in the list.";
Blockly.Msg.MATH_ONLIST_TOOLTIP_MIN = "Return the smallest number in the list.";
Blockly.Msg.MATH_ONLIST_TOOLTIP_MODE = "Return a list of the most common item(s) in the list.";
Blockly.Msg.MATH_ONLIST_TOOLTIP_RANDOM = "Return a random element from the list.";
Blockly.Msg.MATH_ONLIST_TOOLTIP_STD_DEV = "Return the standard deviation of the list.";
Blockly.Msg.MATH_ONLIST_TOOLTIP_SUM = "Return the sum of all the numbers in the list.";
Blockly.Msg.MATH_POWER_SYMBOL = "^";
Blockly.Msg.MATH_RANDOM_FLOAT_HELPURL = "http://en.wikipedia.org/wiki/Random_number_generation";
Blockly.Msg.MATH_RANDOM_FLOAT_TITLE_RANDOM = "random fraction";
Blockly.Msg.MATH_RANDOM_FLOAT_TOOLTIP = "Return a random fraction between 0.0 (inclusive) and 1.0 (exclusive).";
Blockly.Msg.MATH_RANDOM_INT_HELPURL = "http://en.wikipedia.org/wiki/Random_number_generation";
Blockly.Msg.MATH_RANDOM_INT_TITLE = "random integer from %1 to %2";
Blockly.Msg.MATH_RANDOM_INT_TOOLTIP = "Return a random integer between the two specified limits, inclusive.";
Blockly.Msg.MATH_ROUND_HELPURL = "http://en.wikipedia.org/wiki/Rounding";
Blockly.Msg.MATH_ROUND_OPERATOR_ROUND = "round";
Blockly.Msg.MATH_ROUND_OPERATOR_ROUNDDOWN = "round down";
Blockly.Msg.MATH_ROUND_OPERATOR_ROUNDUP = "round up";
Blockly.Msg.MATH_ROUND_TOOLTIP = "Round a number up or down.";
Blockly.Msg.MATH_SINGLE_HELPURL = "http://en.wikipedia.org/wiki/Square_root";
Blockly.Msg.MATH_SINGLE_OP_ABSOLUTE = "absolute";
Blockly.Msg.MATH_SINGLE_OP_ROOT = "square root";
Blockly.Msg.MATH_SINGLE_TOOLTIP_ABS = "Return the absolute value of a number.";
Blockly.Msg.MATH_SINGLE_TOOLTIP_EXP = "Return e to the power of a number.";
Blockly.Msg.MATH_SINGLE_TOOLTIP_LN = "Return the natural logarithm of a number.";
Blockly.Msg.MATH_SINGLE_TOOLTIP_LOG10 = "Return the base 10 logarithm of a number.";
Blockly.Msg.MATH_SINGLE_TOOLTIP_NEG = "Return the negation of a number.";
Blockly.Msg.MATH_SINGLE_TOOLTIP_POW10 = "Return 10 to the power of a number.";
Blockly.Msg.MATH_SINGLE_TOOLTIP_ROOT = "Return the square root of a number.";
Blockly.Msg.MATH_SUBTRACTION_SYMBOL = "-";
Blockly.Msg.MATH_TRIG_ACOS = "acos";
Blockly.Msg.MATH_TRIG_ASIN = "asin";
Blockly.Msg.MATH_TRIG_ATAN = "atan";
Blockly.Msg.MATH_TRIG_COS = "cos";
Blockly.Msg.MATH_TRIG_HELPURL = "http://en.wikipedia.org/wiki/Trigonometric_functions";
Blockly.Msg.MATH_TRIG_SIN = "sin";
Blockly.Msg.MATH_TRIG_TAN = "tan";
Blockly.Msg.MATH_TRIG_TOOLTIP_ACOS = "Return the arccosine of a number.";
Blockly.Msg.MATH_TRIG_TOOLTIP_ASIN = "Return the arcsine of a number.";
Blockly.Msg.MATH_TRIG_TOOLTIP_ATAN = "Return the arctangent of a number.";
Blockly.Msg.MATH_TRIG_TOOLTIP_COS = "Return the cosine of a degree (not radian).";
Blockly.Msg.MATH_TRIG_TOOLTIP_SIN = "Return the sine of a degree (not radian).";
Blockly.Msg.MATH_TRIG_TOOLTIP_TAN = "Return the tangent of a degree (not radian).";
Blockly.Msg.ME = "Me";  // untranslated
Blockly.Msg.MENU_SAVE = "save";  // untranslated
Blockly.Msg.MENU_ZOOM = "zoom";  // untranslated
Blockly.Msg.MENU_ZOOM_IN = "zoom in";  // untranslated
Blockly.Msg.MENU_ZOOM_OUT = "zoom out";  // untranslated
Blockly.Msg.MENU_ZOOM_RESET = "reset zoom";  // untranslated
Blockly.Msg.NEW_VARIABLE = "New variable...";
Blockly.Msg.NEW_VARIABLE_TITLE = "New variable name:";
Blockly.Msg.NEW_VARIABLE_TYPED = "make new %1 memory item";  // untranslated
Blockly.Msg.ORDINAL_NUMBER_SUFFIX = "";  // untranslated
Blockly.Msg.PROCEDURES_ALLOW_STATEMENTS = "allow statements";  // untranslated
Blockly.Msg.PROCEDURES_BEFORE_PARAMS = "with:";
Blockly.Msg.PROCEDURES_CALLNORETURN_HELPURL = "http://en.wikipedia.org/wiki/Procedure_%28computer_science%29";
Blockly.Msg.PROCEDURES_CALLNORETURN_TOOLTIP = "Run the user-defined function '%1'.";
Blockly.Msg.PROCEDURES_CALLRETURN_HELPURL = "http://en.wikipedia.org/wiki/Procedure_%28computer_science%29";
Blockly.Msg.PROCEDURES_CALLRETURN_TOOLTIP = "Run the user-defined function '%1' and use its output.";
Blockly.Msg.PROCEDURES_CALL_BEFORE_PARAMS = "with:";
Blockly.Msg.PROCEDURES_CREATE_DO = "Create '%1'";
Blockly.Msg.PROCEDURES_DEFNORETURN_COMMENT = "Describe this function...";  // untranslated
Blockly.Msg.PROCEDURES_DEFNORETURN_DO = "";  // untranslated
Blockly.Msg.PROCEDURES_DEFNORETURN_HELPURL = "http://en.wikipedia.org/wiki/Procedure_%28computer_science%29";
Blockly.Msg.PROCEDURES_DEFNORETURN_PROCEDURE = "do something";
Blockly.Msg.PROCEDURES_DEFNORETURN_TITLE = "to";
Blockly.Msg.PROCEDURES_DEFNORETURN_TOOLTIP = "Creates a function with no output.";
Blockly.Msg.PROCEDURES_DEFRETURN_HELPURL = "http://en.wikipedia.org/wiki/Procedure_%28computer_science%29";
Blockly.Msg.PROCEDURES_DEFRETURN_RETURN = "return";
Blockly.Msg.PROCEDURES_DEFRETURN_TOOLTIP = "Creates a function with an output.";
Blockly.Msg.PROCEDURES_DEF_DUPLICATE_WARNING = "Warning: This function has duplicate parameters.";
Blockly.Msg.PROCEDURES_HIGHLIGHT_DEF = "Highlight function definition";
Blockly.Msg.PROCEDURES_IFRETURN_HELPURL = "http://c2.com/cgi/wiki?GuardClause";  // untranslated
Blockly.Msg.PROCEDURES_IFRETURN_TOOLTIP = "If a value is true, then return a second value.";
Blockly.Msg.PROCEDURES_IFRETURN_WARNING = "Warning: This block may be used only within a function definition.";
Blockly.Msg.PROCEDURES_MUTATORARG_TITLE = "input name:";
Blockly.Msg.PROCEDURES_MUTATORARG_TOOLTIP = "Add an input to the function.";  // untranslated
Blockly.Msg.PROCEDURES_MUTATORCONTAINER_TITLE = "inputs";
Blockly.Msg.PROCEDURES_MUTATORCONTAINER_TOOLTIP = "Add, remove, or reorder inputs to this function.";  // untranslated
Blockly.Msg.PROCEDURES_TITLE = "' procedure";  // untranslated
Blockly.Msg.PROCEDURES_VARIABLES_ERROR = "Error: This block may be used only within the '";  // untranslated
Blockly.Msg.PROCEDURES_VARIABLES_LOOP_ERROR = "Error: This block may be used only within a loop which declares ";  // untranslated
Blockly.Msg.REDO = "Redo";  // untranslated
Blockly.Msg.REMOVE_COMMENT = "Remove Comment";
Blockly.Msg.RENAME_VARIABLE = "Rename variable...";
Blockly.Msg.RENAME_VARIABLE_TITLE = "Rename all '%1' variables to:";
Blockly.Msg.TEXT_APPEND_APPENDTEXT = "append text";
Blockly.Msg.TEXT_APPEND_HELPURL = "https://github.com/google/blockly/wiki/Text#text-modification";  // untranslated
Blockly.Msg.TEXT_APPEND_TO = "to";
Blockly.Msg.TEXT_APPEND_TOOLTIP = "Append some text to variable '%1'.";
Blockly.Msg.TEXT_APPEND_TO_VARNAME_DEFAULT = "text";  // untranslated
Blockly.Msg.TEXT_CHANGECASE_HELPURL = "https://github.com/google/blockly/wiki/Text#adjusting-text-case";  // untranslated
Blockly.Msg.TEXT_CHANGECASE_OPERATOR_LOWERCASE = "to lower case";
Blockly.Msg.TEXT_CHANGECASE_OPERATOR_TITLECASE = "to Title Case";
Blockly.Msg.TEXT_CHANGECASE_OPERATOR_UPPERCASE = "to UPPER CASE";
Blockly.Msg.TEXT_CHANGECASE_TOOLTIP = "Return a copy of the text in a different case.";
Blockly.Msg.TEXT_CHARAT_FIRST = "get first letter";
Blockly.Msg.TEXT_CHARAT_FROM_END = "get letter # from end";
Blockly.Msg.TEXT_CHARAT_FROM_START = "get letter #";
Blockly.Msg.TEXT_CHARAT_HELPURL = "https://github.com/google/blockly/wiki/Text#extracting-text";  // untranslated
Blockly.Msg.TEXT_CHARAT_INPUT_INTEXT = "in text";
Blockly.Msg.TEXT_CHARAT_LAST = "get last letter";
Blockly.Msg.TEXT_CHARAT_RANDOM = "get random letter";
Blockly.Msg.TEXT_CHARAT_TAIL = "";  // untranslated
Blockly.Msg.TEXT_CHARAT_TOOLTIP = "Returns the letter at the specified position.";
Blockly.Msg.TEXT_CREATE_JOIN_ITEM_TOOLTIP = "Add an item to the text.";
Blockly.Msg.TEXT_CREATE_JOIN_TITLE_JOIN = "join";
Blockly.Msg.TEXT_CREATE_JOIN_TOOLTIP = "Add, remove, or reorder sections to reconfigure this text block.";
Blockly.Msg.TEXT_GET_SUBSTRING_END_FROM_END = "to letter # from end";
Blockly.Msg.TEXT_GET_SUBSTRING_END_FROM_START = "to letter #";
Blockly.Msg.TEXT_GET_SUBSTRING_END_LAST = "to last letter";
Blockly.Msg.TEXT_GET_SUBSTRING_HELPURL = "https://github.com/google/blockly/wiki/Text#extracting-a-region-of-text";  // untranslated
Blockly.Msg.TEXT_GET_SUBSTRING_INPUT_IN_TEXT = "in text";
Blockly.Msg.TEXT_GET_SUBSTRING_START_FIRST = "get substring from first letter";
Blockly.Msg.TEXT_GET_SUBSTRING_START_FROM_END = "get substring from letter # from end";
Blockly.Msg.TEXT_GET_SUBSTRING_START_FROM_START = "get substring from letter #";
Blockly.Msg.TEXT_GET_SUBSTRING_TAIL = "";  // untranslated
Blockly.Msg.TEXT_GET_SUBSTRING_TOOLTIP = "Returns a specified portion of the text.";
Blockly.Msg.TEXT_INDEXOF_HELPURL = "https://github.com/google/blockly/wiki/Text#finding-text";  // untranslated
Blockly.Msg.TEXT_INDEXOF_INPUT_INTEXT = "in text";
Blockly.Msg.TEXT_INDEXOF_OPERATOR_FIRST = "find first occurrence of text";
Blockly.Msg.TEXT_INDEXOF_OPERATOR_LAST = "find last occurrence of text";
Blockly.Msg.TEXT_INDEXOF_TAIL = "";  // untranslated
Blockly.Msg.TEXT_INDEXOF_TOOLTIP = "Returns the index of the first/last occurrence of first text in the second text.  Returns 0 if text is not found.";
Blockly.Msg.TEXT_ISEMPTY_HELPURL = "https://github.com/google/blockly/wiki/Text#checking-for-empty-text";  // untranslated
Blockly.Msg.TEXT_ISEMPTY_TITLE = "%1 is empty";
Blockly.Msg.TEXT_ISEMPTY_TOOLTIP = "Returns true if the provided text is empty.";
Blockly.Msg.TEXT_JOIN_HELPURL = "https://github.com/google/blockly/wiki/Text#text-creation";  // untranslated
Blockly.Msg.TEXT_JOIN_TITLE_CREATEWITH = "create text with";
Blockly.Msg.TEXT_JOIN_TOOLTIP = "Create a piece of text by joining together any number of items.";
Blockly.Msg.TEXT_LENGTH_HELPURL = "https://github.com/google/blockly/wiki/Text#text-modification";  // untranslated
Blockly.Msg.TEXT_LENGTH_TITLE = "length of %1";
Blockly.Msg.TEXT_LENGTH_TOOLTIP = "Returns the number of letters (including spaces) in the provided text.";
Blockly.Msg.TEXT_PRINT_HELPURL = "https://github.com/google/blockly/wiki/Text#printing-text";  // untranslated
Blockly.Msg.TEXT_PRINT_TITLE = "print %1";
Blockly.Msg.TEXT_PRINT_TOOLTIP = "Print the specified text, number or other value.";
Blockly.Msg.TEXT_PROMPT_HELPURL = "https://github.com/google/blockly/wiki/Text#getting-input-from-the-user";  // untranslated
Blockly.Msg.TEXT_PROMPT_TOOLTIP_NUMBER = "Prompt for user for a number.";
Blockly.Msg.TEXT_PROMPT_TOOLTIP_TEXT = "Prompt for user for some text.";
Blockly.Msg.TEXT_PROMPT_TYPE_NUMBER = "prompt for number with message";
Blockly.Msg.TEXT_PROMPT_TYPE_TEXT = "prompt for text with message";
Blockly.Msg.TEXT_TEXT_HELPURL = "http://en.wikipedia.org/wiki/String_(computer_science)";
Blockly.Msg.TEXT_TEXT_TOOLTIP = "A letter, word, or line of text.";
Blockly.Msg.TEXT_TRIM_HELPURL = "https://github.com/google/blockly/wiki/Text#trimming-removing-spaces";  // untranslated
Blockly.Msg.TEXT_TRIM_OPERATOR_BOTH = "trim spaces from both sides";
Blockly.Msg.TEXT_TRIM_OPERATOR_LEFT = "trim spaces from left side";
Blockly.Msg.TEXT_TRIM_OPERATOR_RIGHT = "trim spaces from right side";
Blockly.Msg.TEXT_TRIM_TOOLTIP = "Return a copy of the text with spaces removed from one or both ends.";
Blockly.Msg.TODAY = "Today";  // untranslated
Blockly.Msg.TOOLBOX_ACTION = "Action";  // untranslated
Blockly.Msg.TOOLBOX_COLOUR = "Colours";  // untranslated
Blockly.Msg.TOOLBOX_COMMUNICATION = "Messages";  // untranslated
Blockly.Msg.TOOLBOX_CONTENT_COMPARE_TAG_EXAMPLE_TAG = "enemy";  // untranslated
Blockly.Msg.TOOLBOX_CONTENT_FIND_TAG_EXAMPLE_TAG = "scorekeeper";  // untranslated
Blockly.Msg.TOOLBOX_CONTENT_LOG_THIS_WORKS = "This works!";  // untranslated
Blockly.Msg.TOOLBOX_CONTENT_SCENE_TO = "gameover";  // untranslated
Blockly.Msg.TOOLBOX_CONTROL = "Logic";  // untranslated
Blockly.Msg.TOOLBOX_DECISION = "Decisions";  // untranslated
Blockly.Msg.TOOLBOX_DETECT = "Detect";  // untranslated
Blockly.Msg.TOOLBOX_DISPLAY = "Display";  // untranslated
Blockly.Msg.TOOLBOX_DRIVE = "Drive";  // untranslated
Blockly.Msg.TOOLBOX_EVENTS = "Events";  // untranslated
Blockly.Msg.TOOLBOX_LIGHT = "Lights";  // untranslated
Blockly.Msg.TOOLBOX_LIST = "Lists";  // untranslated
Blockly.Msg.TOOLBOX_LOOP = "Loops";  // untranslated
Blockly.Msg.TOOLBOX_MATH = "Numbers";  // untranslated
Blockly.Msg.TOOLBOX_MATH_GROUP = "Math";  // untranslated
Blockly.Msg.TOOLBOX_MORE = "More blocks";  // untranslated
Blockly.Msg.TOOLBOX_MOVE = "Movement";  // untranslated
Blockly.Msg.TOOLBOX_OBJECTS = "Objects";  // untranslated
Blockly.Msg.TOOLBOX_OTHER = "Other...";  // untranslated
Blockly.Msg.TOOLBOX_PROCEDURE = "Functions";  // untranslated
Blockly.Msg.TOOLBOX_ROTATE = "Rotations";  // untranslated
Blockly.Msg.TOOLBOX_SENSOR = "Sensors";  // untranslated
Blockly.Msg.TOOLBOX_SOUND = "Sounds";  // untranslated
Blockly.Msg.TOOLBOX_TEXT = "Text";  // untranslated
Blockly.Msg.TOOLBOX_TIME = "Time";  // untranslated
Blockly.Msg.TOOLBOX_VARIABLE = "Memory";  // untranslated
Blockly.Msg.TOOLBOX_VECTOR = "Coordinates and directions";  // untranslated
Blockly.Msg.TOOLBOX_WAIT = "Wait";  // untranslated
Blockly.Msg.UI_BLOCKS_HEADER = "Blocks";  // untranslated
Blockly.Msg.UI_GENERATED_CODE = "generated code";  // untranslated
Blockly.Msg.UI_LOAD = "Loading...";  // untranslated
Blockly.Msg.UI_LOAD_FAILURE = "Oops! Something went wrong while loading the file...";  // untranslated
Blockly.Msg.UI_NAME_FILE_MSG = "Please enter a name.";  // untranslated
Blockly.Msg.UI_SAVE = "Saving...";  // untranslated
Blockly.Msg.UI_SAVE_FAILURE = "Oops! Something went wrong while saving the file...";  // untranslated
Blockly.Msg.UI_UNNAMED_FILE = "unnamed file";  // untranslated
Blockly.Msg.UNDO = "Undo";  // untranslated
Blockly.Msg.UNITY_CODE_BLOCK_DEFAULT_CODE = "print({QUOTE}Hello World C# code!{QUOTE});";  // untranslated
Blockly.Msg.UNITY_CODE_BLOCK_DEFAULT_NAME = "my action";  // untranslated
Blockly.Msg.UNITY_CODE_BLOCK_TITLE = "new block";  // untranslated
Blockly.Msg.UNITY_EVENTS_COLLIDE_OPT_ENTER = "just";  // untranslated
Blockly.Msg.UNITY_EVENTS_COLLIDE_OPT_EXIT = "no longer";  // untranslated
Blockly.Msg.UNITY_EVENTS_COLLIDE_OPT_STAY = "still";  // untranslated
Blockly.Msg.UNITY_EVENTS_COLLIDE_PARAM_OBJ = "the object I collided with";  // untranslated
Blockly.Msg.UNITY_EVENTS_COLLIDE_PARAM_OBJ_DEFNAME = "collidedObject";  // untranslated
Blockly.Msg.UNITY_EVENTS_COLLIDE_PARAM_SPEED = "the speed I collided with";  // untranslated
Blockly.Msg.UNITY_EVENTS_COLLIDE_PARAM_SPEED_DEFNAME = "collisionSpeed";  // untranslated
Blockly.Msg.UNITY_EVENTS_COLLIDE_PARAM_VECTOR = "the speed I collided with";  // untranslated
Blockly.Msg.UNITY_EVENTS_COLLIDE_PARAM_VECTOR_DEFNAME = "collisionVector";  // untranslated
Blockly.Msg.UNITY_EVENTS_COLLIDE_TITLE_1 = "when I";  // untranslated
Blockly.Msg.UNITY_EVENTS_COLLIDE_TITLE_2 = "hit something";  // untranslated
Blockly.Msg.UNITY_EVENTS_JOINTBREAKS_PARAM_OBJ = "the object on the other side of the joint";  // untranslated
Blockly.Msg.UNITY_EVENTS_JOINTBREAKS_PARAM_OBJ_DEFNAME = "otherSideObject";  // untranslated
Blockly.Msg.UNITY_EVENTS_JOINTBREAKS_TITLE = "when a joint breaks";  // untranslated
Blockly.Msg.UNITY_EVENTS_MESSAGE_DEFAULT = "do something";  // untranslated
Blockly.Msg.UNITY_EVENTS_MESSAGE_RECEIVE_ARG_TITLE_1 = "when I receive message";  // untranslated
Blockly.Msg.UNITY_EVENTS_MESSAGE_RECEIVE_ARG_TITLE_2 = "with information";  // untranslated
Blockly.Msg.UNITY_EVENTS_MESSAGE_RECEIVE_TITLE_1 = "when I receive message";  // untranslated
Blockly.Msg.UNITY_EVENTS_MESSAGE_RECEIVE_TITLE_2 = "";  // untranslated
Blockly.Msg.UNITY_EVENTS_MESSAGE_SEND_ARG_TITLE_1 = "send message";  // untranslated
Blockly.Msg.UNITY_EVENTS_MESSAGE_SEND_ARG_TITLE_2 = "to";  // untranslated
Blockly.Msg.UNITY_EVENTS_MESSAGE_SEND_ARG_TITLE_3 = "with information";  // untranslated
Blockly.Msg.UNITY_EVENTS_MESSAGE_SEND_REQUIRE_RECEIVER = "require someone listening";  // untranslated
Blockly.Msg.UNITY_EVENTS_MESSAGE_SEND_TITLE_1 = "send message";  // untranslated
Blockly.Msg.UNITY_EVENTS_MESSAGE_SEND_TITLE_2 = "to";  // untranslated
Blockly.Msg.UNITY_EVENTS_MOUSECLICK_OPT_DOWN = "starts a click";  // untranslated
Blockly.Msg.UNITY_EVENTS_MOUSECLICK_OPT_STAY = "is still pressed down";  // untranslated
Blockly.Msg.UNITY_EVENTS_MOUSECLICK_OPT_UP = "is released";  // untranslated
Blockly.Msg.UNITY_EVENTS_MOUSECLICK_TITLE_1 = "when a mouse button";  // untranslated
Blockly.Msg.UNITY_EVENTS_MOUSECLICK_TITLE_2 = "on me";  // untranslated
Blockly.Msg.UNITY_EVENTS_MOUSEHOVER_OPT_ENTER = "just started";  // untranslated
Blockly.Msg.UNITY_EVENTS_MOUSEHOVER_OPT_EXIT = "is no longer";  // untranslated
Blockly.Msg.UNITY_EVENTS_MOUSEHOVER_OPT_STAY = "is still";  // untranslated
Blockly.Msg.UNITY_EVENTS_MOUSEHOVER_TITLE_1 = "when the mouse";  // untranslated
Blockly.Msg.UNITY_EVENTS_MOUSEHOVER_TITLE_2 = "hovering over me";  // untranslated
Blockly.Msg.UNITY_EVENTS_START_TITLE = "when I start";  // untranslated
Blockly.Msg.UNITY_EVENTS_TRIGGER_OPT_ENTER = "just entered";  // untranslated
Blockly.Msg.UNITY_EVENTS_TRIGGER_OPT_EXIT = "just exited";  // untranslated
Blockly.Msg.UNITY_EVENTS_TRIGGER_OPT_STAY = "is still in";  // untranslated
Blockly.Msg.UNITY_EVENTS_TRIGGER_PARAM_OBJ = "the other object";  // untranslated
Blockly.Msg.UNITY_EVENTS_TRIGGER_PARAM_OBJ_DEFNAME = "otherObject";  // untranslated
Blockly.Msg.UNITY_EVENTS_TRIGGER_TITLE_1 = "when something";  // untranslated
Blockly.Msg.UNITY_EVENTS_TRIGGER_TITLE_2 = "my trigger area";  // untranslated
Blockly.Msg.UNITY_EVENTS_UPDATE_TITLE = "repeat every frame";  // untranslated
Blockly.Msg.UNITY_GENERATED_CODE_WARNING = "DO NOT CHANGE THIS FILE!#The code in this file is automatically generated!#Changes to the code will be overwritten when the file is resaved again from inside Vubbi.";  // untranslated
Blockly.Msg.UNITY_INPUT_GETKEY_OPT_DOWN = "just pressed down";  // untranslated
Blockly.Msg.UNITY_INPUT_GETKEY_OPT_STAY = "still pressed down";  // untranslated
Blockly.Msg.UNITY_INPUT_GETKEY_OPT_UP = "just released";  // untranslated
Blockly.Msg.UNITY_INPUT_GETKEY_TITLE_1 = "button";  // untranslated
Blockly.Msg.UNITY_INPUT_GETKEY_TITLE_2 = "";  // untranslated
Blockly.Msg.UNITY_KEYCODE_Alpha0 = "alphanumeric keyboard 0";  // untranslated
Blockly.Msg.UNITY_KEYCODE_Alpha1 = "alphanumeric keyboard 1";  // untranslated
Blockly.Msg.UNITY_KEYCODE_Alpha2 = "alphanumeric keyboard 2";  // untranslated
Blockly.Msg.UNITY_KEYCODE_Alpha3 = "alphanumeric keyboard 3";  // untranslated
Blockly.Msg.UNITY_KEYCODE_Alpha4 = "alphanumeric keyboard 4";  // untranslated
Blockly.Msg.UNITY_KEYCODE_Alpha5 = "alphanumeric keyboard 5";  // untranslated
Blockly.Msg.UNITY_KEYCODE_Alpha6 = "alphanumeric keyboard 6";  // untranslated
Blockly.Msg.UNITY_KEYCODE_Alpha7 = "alphanumeric keyboard 7";  // untranslated
Blockly.Msg.UNITY_KEYCODE_Alpha8 = "alphanumeric keyboard 8";  // untranslated
Blockly.Msg.UNITY_KEYCODE_Alpha9 = "alphanumeric keyboard 9";  // untranslated
Blockly.Msg.UNITY_KEYCODE_AltGr = "alt Gr key";  // untranslated
Blockly.Msg.UNITY_KEYCODE_Ampersand = "ampersand key '&'";  // untranslated
Blockly.Msg.UNITY_KEYCODE_Asterisk = "asterisk key '*'";  // untranslated
Blockly.Msg.UNITY_KEYCODE_At = "at key '@'";  // untranslated
Blockly.Msg.UNITY_KEYCODE_BackQuote = "back quote key ";  // untranslated
Blockly.Msg.UNITY_KEYCODE_Backslash = "backslash key '\'";  // untranslated
Blockly.Msg.UNITY_KEYCODE_Backspace = "backspace";  // untranslated
Blockly.Msg.UNITY_KEYCODE_Break = "break key";  // untranslated
Blockly.Msg.UNITY_KEYCODE_CapsLock = "capslock key";  // untranslated
Blockly.Msg.UNITY_KEYCODE_Caret = "caret key '^'";  // untranslated
Blockly.Msg.UNITY_KEYCODE_Clear = "'clear'";  // untranslated
Blockly.Msg.UNITY_KEYCODE_Colon = "colon ':' key";  // untranslated
Blockly.Msg.UNITY_KEYCODE_Comma = "comma ',' key";  // untranslated
Blockly.Msg.UNITY_KEYCODE_Delete = "delete";  // untranslated
Blockly.Msg.UNITY_KEYCODE_Dollar = "dollar sign key '$'";  // untranslated
Blockly.Msg.UNITY_KEYCODE_DoubleQuote = "double quote '''";  // untranslated
Blockly.Msg.UNITY_KEYCODE_DownArrow = "arrow key down";  // untranslated
Blockly.Msg.UNITY_KEYCODE_End = "'end'";  // untranslated
Blockly.Msg.UNITY_KEYCODE_Equals = "equals '=' key";  // untranslated
Blockly.Msg.UNITY_KEYCODE_Escape = "escape";  // untranslated
Blockly.Msg.UNITY_KEYCODE_Exclaim = "exclamation mark '!'";  // untranslated
Blockly.Msg.UNITY_KEYCODE_F1 = "F1";  // untranslated
Blockly.Msg.UNITY_KEYCODE_F10 = "F10";  // untranslated
Blockly.Msg.UNITY_KEYCODE_F11 = "F11";  // untranslated
Blockly.Msg.UNITY_KEYCODE_F12 = "F12";  // untranslated
Blockly.Msg.UNITY_KEYCODE_F13 = "F13";  // untranslated
Blockly.Msg.UNITY_KEYCODE_F14 = "F14";  // untranslated
Blockly.Msg.UNITY_KEYCODE_F15 = "F15";  // untranslated
Blockly.Msg.UNITY_KEYCODE_F2 = "F2";  // untranslated
Blockly.Msg.UNITY_KEYCODE_F3 = "F3";  // untranslated
Blockly.Msg.UNITY_KEYCODE_F4 = "F4";  // untranslated
Blockly.Msg.UNITY_KEYCODE_F5 = "F5";  // untranslated
Blockly.Msg.UNITY_KEYCODE_F6 = "F6";  // untranslated
Blockly.Msg.UNITY_KEYCODE_F7 = "F7";  // untranslated
Blockly.Msg.UNITY_KEYCODE_F8 = "F8";  // untranslated
Blockly.Msg.UNITY_KEYCODE_F9 = "F9";  // untranslated
Blockly.Msg.UNITY_KEYCODE_Greater = "greater than '>' key";  // untranslated
Blockly.Msg.UNITY_KEYCODE_Hash = "hash key '#'";  // untranslated
Blockly.Msg.UNITY_KEYCODE_Help = "help key";  // untranslated
Blockly.Msg.UNITY_KEYCODE_Home = "'home'";  // untranslated
Blockly.Msg.UNITY_KEYCODE_Insert = "'insert'";  // untranslated
Blockly.Msg.UNITY_KEYCODE_Keypad0 = "numeric keyboard 0";  // untranslated
Blockly.Msg.UNITY_KEYCODE_Keypad1 = "numeric keyboard 1";  // untranslated
Blockly.Msg.UNITY_KEYCODE_Keypad2 = "numeric keyboard 2";  // untranslated
Blockly.Msg.UNITY_KEYCODE_Keypad3 = "numeric keyboard 3";  // untranslated
Blockly.Msg.UNITY_KEYCODE_Keypad4 = "numeric keyboard 4";  // untranslated
Blockly.Msg.UNITY_KEYCODE_Keypad5 = "numeric keyboard 5";  // untranslated
Blockly.Msg.UNITY_KEYCODE_Keypad6 = "numeric keyboard 6";  // untranslated
Blockly.Msg.UNITY_KEYCODE_Keypad7 = "numeric keyboard 7";  // untranslated
Blockly.Msg.UNITY_KEYCODE_Keypad8 = "numeric keyboard 8";  // untranslated
Blockly.Msg.UNITY_KEYCODE_Keypad9 = "numeric keyboard 9";  // untranslated
Blockly.Msg.UNITY_KEYCODE_KeypadDivide = "numeric keyboard '/'";  // untranslated
Blockly.Msg.UNITY_KEYCODE_KeypadEnter = "numeric keyboard enter";  // untranslated
Blockly.Msg.UNITY_KEYCODE_KeypadEquals = "numeric keyboard '='";  // untranslated
Blockly.Msg.UNITY_KEYCODE_KeypadMinus = "numeric keyboard '-'";  // untranslated
Blockly.Msg.UNITY_KEYCODE_KeypadMultiply = "numeric keyboard '*'";  // untranslated
Blockly.Msg.UNITY_KEYCODE_KeypadPeriod = "numeric keyboard '.'";  // untranslated
Blockly.Msg.UNITY_KEYCODE_KeypadPlus = "numeric keyboard '+'";  // untranslated
Blockly.Msg.UNITY_KEYCODE_LeftAlt = "left Alt key";  // untranslated
Blockly.Msg.UNITY_KEYCODE_LeftApple = "left Command key";  // untranslated
Blockly.Msg.UNITY_KEYCODE_LeftArrow = "arrow key left";  // untranslated
Blockly.Msg.UNITY_KEYCODE_LeftBracket = "left square bracket key '['";  // untranslated
Blockly.Msg.UNITY_KEYCODE_LeftCommand = "left Command key";  // untranslated
Blockly.Msg.UNITY_KEYCODE_LeftControl = "left Control key";  // untranslated
Blockly.Msg.UNITY_KEYCODE_LeftParen = "left Parenthesis key '('";  // untranslated
Blockly.Msg.UNITY_KEYCODE_LeftShift = "left shift key";  // untranslated
Blockly.Msg.UNITY_KEYCODE_LeftWindows = "left Windows key";  // untranslated
Blockly.Msg.UNITY_KEYCODE_Less = "less than '<' key";  // untranslated
Blockly.Msg.UNITY_KEYCODE_Menu = "menu key";  // untranslated
Blockly.Msg.UNITY_KEYCODE_Minus = "minus '-' key";  // untranslated
Blockly.Msg.UNITY_KEYCODE_Mouse0 = "first (primary) mouse button";  // untranslated
Blockly.Msg.UNITY_KEYCODE_Mouse1 = "second (secondary) mouse button";  // untranslated
Blockly.Msg.UNITY_KEYCODE_Mouse2 = "third mouse button";  // untranslated
Blockly.Msg.UNITY_KEYCODE_Numlock = "numlock key";  // untranslated
Blockly.Msg.UNITY_KEYCODE_PageDown = "'page down'";  // untranslated
Blockly.Msg.UNITY_KEYCODE_PageUp = "'page up'";  // untranslated
Blockly.Msg.UNITY_KEYCODE_Pause = "'pause' (PC)";  // untranslated
Blockly.Msg.UNITY_KEYCODE_Period = "period '.' key";  // untranslated
Blockly.Msg.UNITY_KEYCODE_Plus = "plus key '+'";  // untranslated
Blockly.Msg.UNITY_KEYCODE_Print = "print key";  // untranslated
Blockly.Msg.UNITY_KEYCODE_Question = "question mark '?' key";  // untranslated
Blockly.Msg.UNITY_KEYCODE_Quote = "quote key '";  // untranslated
Blockly.Msg.UNITY_KEYCODE_Return = "enter";  // untranslated
Blockly.Msg.UNITY_KEYCODE_RightAlt = "right Alt key";  // untranslated
Blockly.Msg.UNITY_KEYCODE_RightApple = "right Command key";  // untranslated
Blockly.Msg.UNITY_KEYCODE_RightArrow = "arrow key right";  // untranslated
Blockly.Msg.UNITY_KEYCODE_RightBracket = "right square bracket key ']'";  // untranslated
Blockly.Msg.UNITY_KEYCODE_RightCommand = "right Command key";  // untranslated
Blockly.Msg.UNITY_KEYCODE_RightControl = "right Control key";  // untranslated
Blockly.Msg.UNITY_KEYCODE_RightParen = "right Parenthesis key ')'";  // untranslated
Blockly.Msg.UNITY_KEYCODE_RightShift = "right shift key";  // untranslated
Blockly.Msg.UNITY_KEYCODE_RightWindows = "right Windows key";  // untranslated
Blockly.Msg.UNITY_KEYCODE_ScrollLock = "scroll lock key";  // untranslated
Blockly.Msg.UNITY_KEYCODE_Semicolon = "semicolon ';' key";  // untranslated
Blockly.Msg.UNITY_KEYCODE_Slash = "slash '/' key";  // untranslated
Blockly.Msg.UNITY_KEYCODE_Space = "space";  // untranslated
Blockly.Msg.UNITY_KEYCODE_SysReq = "sys req key";  // untranslated
Blockly.Msg.UNITY_KEYCODE_Tab = "tab";  // untranslated
Blockly.Msg.UNITY_KEYCODE_Underscore = "underscore '_' key";  // untranslated
Blockly.Msg.UNITY_KEYCODE_UpArrow = "arrow key up";  // untranslated
Blockly.Msg.UNITY_LOG_TITLE = "print";  // untranslated
Blockly.Msg.UNITY_MEMORY_TITLE = "memory";  // untranslated
Blockly.Msg.UNITY_MEMORY_TOOLTIP = "The memory of this script.";  // untranslated
Blockly.Msg.UNITY_OBJECTS_CREATE_AND_GET_TITLE = "make clone of";  // untranslated
Blockly.Msg.UNITY_OBJECTS_CREATE_TITLE = "make clone of";  // untranslated
Blockly.Msg.UNITY_OBJECTS_DESTROY_TITLE = "destroy";  // untranslated
Blockly.Msg.UNITY_OBJECTS_FIND_TAG_DEFAULT_TAG = "scorekeeper";  // untranslated
Blockly.Msg.UNITY_OBJECTS_FIND_TAG_TITLE = "find GameObject with tag";  // untranslated
Blockly.Msg.UNITY_OBJECTS_TAG_COMPARE_TITLE_1 = "tag of";  // untranslated
Blockly.Msg.UNITY_OBJECTS_TAG_COMPARE_TITLE_2 = "is";  // untranslated
Blockly.Msg.UNITY_OBJECTS_TAG_OF_TITLE = "tag of";  // untranslated
Blockly.Msg.UNITY_PARAMOUTPUT_EXECUTE_TITLE = "and do";  // untranslated
Blockly.Msg.UNITY_PARAMOUTPUT_TITLE_1 = "remember";  // untranslated
Blockly.Msg.UNITY_PARAMOUTPUT_TITLE_2 = "in";  // untranslated
Blockly.Msg.UNITY_PHYSICS_ANGULARSPEED_SET_TITLE_1 = "set velocity (°/s) of dyn. rigidbody of";  // untranslated
Blockly.Msg.UNITY_PHYSICS_ANGULARSPEED_SET_TITLE_2 = "to";  // untranslated
Blockly.Msg.UNITY_PHYSICS_ANGULARSPEED_TITLE = "angular velocity (°/s) of";  // untranslated
Blockly.Msg.UNITY_PHYSICS_PUSH_TITLE_1 = "push";  // untranslated
Blockly.Msg.UNITY_PHYSICS_PUSH_TITLE_2 = "with force";  // untranslated
Blockly.Msg.UNITY_PHYSICS_TORQUE_TITLE_1 = "apply to";  // untranslated
Blockly.Msg.UNITY_PHYSICS_TORQUE_TITLE_2 = "a rotational force of";  // untranslated
Blockly.Msg.UNITY_PHYSICS_VELOCITY_SET_TITLE_1 = "set velocity (unit/s) of dyn. rigidbody of";  // untranslated
Blockly.Msg.UNITY_PHYSICS_VELOCITY_SET_TITLE_2 = "to";  // untranslated
Blockly.Msg.UNITY_PHYSICS_VELOCITY_TITLE = "velocity (unit/s) of";  // untranslated
Blockly.Msg.UNITY_QUATERNION_ANGLEAXIS2D_TITLE = "° (2D)";  // untranslated
Blockly.Msg.UNITY_QUATERNION_ANGLEAXIS_TITLE_1 = "° around ";  // untranslated
Blockly.Msg.UNITY_QUATERNION_ANGLEAXIS_TITLE_2 = " (3D)";  // untranslated
Blockly.Msg.UNITY_QUATERNION_APPLY_VECTOR_TITLE = " rotated by ";  // untranslated
Blockly.Msg.UNITY_QUATERNION_COMBINE_TITLE_1 = "combine rotations: rotate first ";  // untranslated
Blockly.Msg.UNITY_QUATERNION_COMBINE_TITLE_2 = " and then ";  // untranslated
Blockly.Msg.UNITY_QUATERNION_GET_ANGLE_2D_TITLE_1 = "2D direction (0°-360°) of ";  // untranslated
Blockly.Msg.UNITY_QUATERNION_GET_ANGLE_TITLE_1 = "difference between rotation ";  // untranslated
Blockly.Msg.UNITY_QUATERNION_GET_ANGLE_TITLE_2 = " and ";  // untranslated
Blockly.Msg.UNITY_QUATERNION_GET_ANGLE_TITLE_3 = " in degrees";  // untranslated
Blockly.Msg.UNITY_QUATERNION_GET_ROTATION_TITLE = "rotation of ";  // untranslated
Blockly.Msg.UNITY_QUATERNION_IDENTITY_TITLE = "not rotated";  // untranslated
Blockly.Msg.UNITY_QUATERNION_INVERSE_TITLE = "inverse rotation of ";  // untranslated
Blockly.Msg.UNITY_QUATERNION_LOOKTOWARDS_2D_OPT_XAXIS_NEG = "negative side of my x-axis";  // untranslated
Blockly.Msg.UNITY_QUATERNION_LOOKTOWARDS_2D_OPT_XAXIS_POS = "positive side of my x-axis";  // untranslated
Blockly.Msg.UNITY_QUATERNION_LOOKTOWARDS_2D_OPT_YAXIS_NEG = "negative side of my y-axis";  // untranslated
Blockly.Msg.UNITY_QUATERNION_LOOKTOWARDS_2D_OPT_YAXIS_POS = "positive side of my y-axis";  // untranslated
Blockly.Msg.UNITY_QUATERNION_LOOKTOWARDS_2D_TITLE_1 = "rotation where the ";  // untranslated
Blockly.Msg.UNITY_QUATERNION_LOOKTOWARDS_2D_TITLE_2 = " points towards ";  // untranslated
Blockly.Msg.UNITY_QUATERNION_LOOKTOWARDS_2D_TITLE_3 = " from ";  // untranslated
Blockly.Msg.UNITY_QUATERNION_LOOKTOWARDS_2D_TITLE_4 = " (2D)";  // untranslated
Blockly.Msg.UNITY_QUATERNION_LOOKTOWARDS_TITLE_1 = "rotation around axis ";  // untranslated
Blockly.Msg.UNITY_QUATERNION_LOOKTOWARDS_TITLE_2 = " where my ";  // untranslated
Blockly.Msg.UNITY_QUATERNION_LOOKTOWARDS_TITLE_3 = " points towards ";  // untranslated
Blockly.Msg.UNITY_QUATERNION_LOOKTOWARDS_TITLE_4 = " from ";  // untranslated
Blockly.Msg.UNITY_QUATERNION_ROTATE_TITLE_1 = "change rotation of ";  // untranslated
Blockly.Msg.UNITY_QUATERNION_ROTATE_TITLE_2 = "with";  // untranslated
Blockly.Msg.UNITY_QUATERNION_SET_ROTATION_TITLE_1 = "set rotation of ";  // untranslated
Blockly.Msg.UNITY_QUATERNION_SET_ROTATION_TITLE_2 = " on ";  // untranslated
Blockly.Msg.UNITY_RAYCAST_RAYCAST_PARAM_DIST = "the distance";  // untranslated
Blockly.Msg.UNITY_RAYCAST_RAYCAST_PARAM_DIST_DEFNAME = "distance";  // untranslated
Blockly.Msg.UNITY_RAYCAST_RAYCAST_PARAM_NORMAL = "the normal vector where the laser hit";  // untranslated
Blockly.Msg.UNITY_RAYCAST_RAYCAST_PARAM_NORMAL_DEFNAME = "normal";  // untranslated
Blockly.Msg.UNITY_RAYCAST_RAYCAST_PARAM_OBJ = "the object that got hit";  // untranslated
Blockly.Msg.UNITY_RAYCAST_RAYCAST_PARAM_OBJ_DEFNAME = "hitObject";  // untranslated
Blockly.Msg.UNITY_RAYCAST_RAYCAST_PARAM_POINT = "the point where the laser hit";  // untranslated
Blockly.Msg.UNITY_RAYCAST_RAYCAST_PARAM_POINT_DEFNAME = "point";  // untranslated
Blockly.Msg.UNITY_RAYCAST_RAYCAST_TITLE_1 = "shoot a laser";  // untranslated
Blockly.Msg.UNITY_RAYCAST_RAYCAST_TITLE_2 = "from position";  // untranslated
Blockly.Msg.UNITY_RAYCAST_RAYCAST_TITLE_3 = "in direction";  // untranslated
Blockly.Msg.UNITY_RAYCAST_RAYCAST_TITLE_4 = "when it hits do";  // untranslated
Blockly.Msg.UNITY_RENDER_SETSPRITE_TITLE_1 = "set appearance of";  // untranslated
Blockly.Msg.UNITY_RENDER_SETSPRITE_TITLE_2 = "to";  // untranslated
Blockly.Msg.UNITY_SCENE_GOTO_TITLE = "go to scene with name";  // untranslated
Blockly.Msg.UNITY_SCREEN_CAMERA_MAIN_TITLE = "the main camera object";  // untranslated
Blockly.Msg.UNITY_SCREEN_MOUSE_POSITION_TITLE = "pixel position of the mouse on the screen";  // untranslated
Blockly.Msg.UNITY_SCREEN_MOUSE_SCENE_POSITION_2D_TITLE = "position of the mouse in the scene with z=0 (2D)";  // untranslated
Blockly.Msg.UNITY_SCREEN_SCENE_TO_SCREEN_TITLE_1 = "pixel position on screen of coordinate";  // untranslated
Blockly.Msg.UNITY_SCREEN_SCENE_TO_SCREEN_TITLE_2 = "for camera of";  // untranslated
Blockly.Msg.UNITY_SCREEN_SCREEN_SIZE_TITLE = "size of screen in pixels";  // untranslated
Blockly.Msg.UNITY_SCREEN_SCREEN_TO_SCENE_DIR_TITLE_1 = "look direction in scene of pixel position";  // untranslated
Blockly.Msg.UNITY_SCREEN_SCREEN_TO_SCENE_DIR_TITLE_2 = "for camera of";  // untranslated
Blockly.Msg.UNITY_SCREEN_SCREEN_TO_SCENE_TITLE_1 = "coordinate in scene of pixel position";  // untranslated
Blockly.Msg.UNITY_SCREEN_SCREEN_TO_SCENE_TITLE_2 = "for camera of";  // untranslated
Blockly.Msg.UNITY_SCREEN_SCREEN_TO_SCENE_TITLE_3 = "on the plane with normal";  // untranslated
Blockly.Msg.UNITY_SCREEN_SCREEN_TO_SCENE_TITLE_4 = "containing point";  // untranslated
Blockly.Msg.UNITY_THIS = "myself";  // untranslated
Blockly.Msg.UNITY_TIME_DELTA_TITLE = "delta time";  // untranslated
Blockly.Msg.UNITY_TIME_LEVELLOAD_TITLE = "time since start of the scene";  // untranslated
Blockly.Msg.UNITY_TIME_LOOP_TITLE = "time since start of repeat";  // untranslated
Blockly.Msg.UNITY_TIME_REPEAT_TILL_TITLE = "repeat each frame 🕑 while ";  // untranslated
Blockly.Msg.UNITY_TIME_REPEAT_TITLE = "repeat each frame 🕑";  // untranslated
Blockly.Msg.UNITY_TIME_WAITFRAME_TITLE = "wait till next frame 🕑";  // untranslated
Blockly.Msg.UNITY_TIME_WAITTIME_TITLE_1 = "wait";  // untranslated
Blockly.Msg.UNITY_TIME_WAITTIME_TITLE_2 = "second(s) 🕑";  // untranslated
Blockly.Msg.UNITY_TRANSFORM_JUMPTO_TITLE_1 = "jump";  // untranslated
Blockly.Msg.UNITY_TRANSFORM_JUMPTO_TITLE_2 = "to";  // untranslated
Blockly.Msg.UNITY_TRANSFORM_MOVE_TITLE_1 = "jump";  // untranslated
Blockly.Msg.UNITY_TRANSFORM_MOVE_TITLE_2 = "additionally with";  // untranslated
Blockly.Msg.UNITY_TRANSFORM_POSITION_TITLE = "position of";  // untranslated
Blockly.Msg.UNITY_UI_SET_TEXT_TITLE_1 = "set UI text of";  // untranslated
Blockly.Msg.UNITY_UI_SET_TEXT_TITLE_2 = "on";  // untranslated
Blockly.Msg.UNITY_VECTOR_CREATE_X_TITLE = "x";  // untranslated
Blockly.Msg.UNITY_VECTOR_CREATE_Y_TITLE = "y";  // untranslated
Blockly.Msg.UNITY_VECTOR_CREATE_Z_TITLE = "z";  // untranslated
Blockly.Msg.UNITY_VECTOR_FETCH_TITLE_1 = "of";  // untranslated
Blockly.Msg.UNITY_VECTOR_FETCH_X_TITLE = "x of";  // untranslated
Blockly.Msg.UNITY_VECTOR_FETCH_Y_TITLE = "y of";  // untranslated
Blockly.Msg.UNITY_VECTOR_FETCH_Z_TITLE = "z of";  // untranslated
Blockly.Msg.UNITY_VECTOR_LENGTH_TITLE = "length of";  // untranslated
Blockly.Msg.UNITY_VECTOR_MATH_TOOLTIP_ADD = "Gives the element wise sum of two vectors.";  // untranslated
Blockly.Msg.UNITY_VECTOR_MATH_TOOLTIP_MINUS = "Gives the element wise subtraction of two vectors.";  // untranslated
Blockly.Msg.UNITY_VECTOR_MATH_TOOLTIP_MULTIPLY = "Gives the element wise multiplication of two vectors.";  // untranslated
Blockly.Msg.UNITY_VECTOR_MULTIPLY_TITLE = "times";  // untranslated
Blockly.Msg.UNITY_VECTOR_PICK_OPT_BACK = "backward (depth) (0, 0, -1)";  // untranslated
Blockly.Msg.UNITY_VECTOR_PICK_OPT_DOWN = "down (0, -1, 0)";  // untranslated
Blockly.Msg.UNITY_VECTOR_PICK_OPT_FORWARD = "forward (depth) (0, 0, 1)";  // untranslated
Blockly.Msg.UNITY_VECTOR_PICK_OPT_LEFT = "left (-1, 0, 0)";  // untranslated
Blockly.Msg.UNITY_VECTOR_PICK_OPT_ONE = "one (1, 1, 1)";  // untranslated
Blockly.Msg.UNITY_VECTOR_PICK_OPT_RIGHT = "right (1, 0, 0)";  // untranslated
Blockly.Msg.UNITY_VECTOR_PICK_OPT_UP = "up (0, 1, 0)";  // untranslated
Blockly.Msg.UNITY_VECTOR_PICK_OPT_ZERO = "zero (0, 0, 0)";  // untranslated
Blockly.Msg.UNITY_VECTOR_PRODUCT_OPTION_CROSS = "cross";  // untranslated
Blockly.Msg.UNITY_VECTOR_PRODUCT_OPTION_DOT = "dot";  // untranslated
Blockly.Msg.UNITY_VECTOR_PRODUCT_TITLE_1 = "product of";  // untranslated
Blockly.Msg.UNITY_VECTOR_PRODUCT_TITLE_2 = "and";  // untranslated
Blockly.Msg.UNITY_VECTOR_TOSIZE_TITLE = "scaled to length";  // untranslated
Blockly.Msg.UNITY_VECTOR_TRANSFORMPOINT_TOLOCAL_TITLE_1 = "position local to";  // untranslated
Blockly.Msg.UNITY_VECTOR_TRANSFORMPOINT_TOLOCAL_TITLE_2 = "of position";  // untranslated
Blockly.Msg.UNITY_VECTOR_TRANSFORMPOINT_TOLOCAL_TITLE_3 = "in the world";  // untranslated
Blockly.Msg.UNITY_VECTOR_TRANSFORMPOINT_TOWORLD_TITLE_1 = "position in the world of position";  // untranslated
Blockly.Msg.UNITY_VECTOR_TRANSFORMPOINT_TOWORLD_TITLE_2 = "local to";  // untranslated
Blockly.Msg.VARIABLES_DEFAULT_NAME = "item";
Blockly.Msg.VARIABLES_GET_CREATE_SET = "Create 'set %1'";
Blockly.Msg.VARIABLES_GET_HELPURL = "https://github.com/google/blockly/wiki/Variables#get";  // untranslated
Blockly.Msg.VARIABLES_GET_TOOLTIP = "Returns the value of this variable.";
Blockly.Msg.VARIABLES_SET = "set %1 to %2";
Blockly.Msg.VARIABLES_SET_CREATE_GET = "Create 'get %1'";
Blockly.Msg.VARIABLES_SET_HELPURL = "https://github.com/google/blockly/wiki/Variables#set";  // untranslated
Blockly.Msg.VARIABLES_SET_TOOLTIP = "Sets this variable to be equal to the input.";
Blockly.Msg.VARIABLES_TYPE_ARRAY_BOOLEAN = "List Boolean";  // untranslated
Blockly.Msg.VARIABLES_TYPE_ARRAY_COLOUR = "List Colour";  // untranslated
Blockly.Msg.VARIABLES_TYPE_ARRAY_CONNECTION = "List Connection";  // untranslated
Blockly.Msg.VARIABLES_TYPE_ARRAY_NUMBER = "List Number";  // untranslated
Blockly.Msg.VARIABLES_TYPE_ARRAY_STRING = "List String";  // untranslated
Blockly.Msg.VARIABLES_TYPE_BOOLEAN = "Boolean";  // untranslated
Blockly.Msg.VARIABLES_TYPE_COLOUR = "Colour";  // untranslated
Blockly.Msg.VARIABLES_TYPE_CONNECTION = "Connection";  // untranslated
Blockly.Msg.VARIABLES_TYPE_GAMEOBJECT = "GameObject";  // untranslated
Blockly.Msg.VARIABLES_TYPE_NUMBER = "Number";  // untranslated
Blockly.Msg.VARIABLES_TYPE_QUATERNION = "Rotation";  // untranslated
Blockly.Msg.VARIABLES_TYPE_SPRITE = "Sprite";  // untranslated
Blockly.Msg.VARIABLES_TYPE_STRING = "String";  // untranslated
Blockly.Msg.VARIABLES_TYPE_VECTOR3 = "Vector3";  // untranslated
Blockly.Msg.MATH_CHANGE_TITLE_ITEM = Blockly.Msg.VARIABLES_DEFAULT_NAME;
Blockly.Msg.PROCEDURES_DEFRETURN_TITLE = Blockly.Msg.PROCEDURES_DEFNORETURN_TITLE;
Blockly.Msg.CONTROLS_IF_IF_TITLE_IF = Blockly.Msg.CONTROLS_IF_MSG_IF;
Blockly.Msg.CONTROLS_WHILEUNTIL_INPUT_DO = Blockly.Msg.CONTROLS_REPEAT_INPUT_DO;
Blockly.Msg.CONTROLS_IF_MSG_THEN = Blockly.Msg.CONTROLS_REPEAT_INPUT_DO;
Blockly.Msg.CONTROLS_IF_ELSE_TITLE_ELSE = Blockly.Msg.CONTROLS_IF_MSG_ELSE;
Blockly.Msg.PROCEDURES_DEFRETURN_PROCEDURE = Blockly.Msg.PROCEDURES_DEFNORETURN_PROCEDURE;
Blockly.Msg.LISTS_GET_SUBLIST_INPUT_IN_LIST = Blockly.Msg.LISTS_INLIST;
Blockly.Msg.VARIABLES_GET_ITEM = Blockly.Msg.VARIABLES_DEFAULT_NAME;
Blockly.Msg.PROCEDURES_DEFRETURN_DO = Blockly.Msg.PROCEDURES_DEFNORETURN_DO;
Blockly.Msg.CONTROLS_IF_ELSEIF_TITLE_ELSEIF = Blockly.Msg.CONTROLS_IF_MSG_ELSEIF;
Blockly.Msg.LISTS_GET_INDEX_INPUT_IN_LIST = Blockly.Msg.LISTS_INLIST;
Blockly.Msg.CONTROLS_FOREACH_INPUT_DO = Blockly.Msg.CONTROLS_REPEAT_INPUT_DO;
Blockly.Msg.LISTS_SET_INDEX_INPUT_IN_LIST = Blockly.Msg.LISTS_INLIST;
Blockly.Msg.CONTROLS_FOR_INPUT_DO = Blockly.Msg.CONTROLS_REPEAT_INPUT_DO;
Blockly.Msg.LISTS_CREATE_WITH_ITEM_TITLE = Blockly.Msg.VARIABLES_DEFAULT_NAME;
Blockly.Msg.TEXT_APPEND_VARIABLE = Blockly.Msg.VARIABLES_DEFAULT_NAME;
Blockly.Msg.TEXT_CREATE_JOIN_ITEM_TITLE_ITEM = Blockly.Msg.VARIABLES_DEFAULT_NAME;
Blockly.Msg.LISTS_INDEX_OF_INPUT_IN_LIST = Blockly.Msg.LISTS_INLIST;
Blockly.Msg.PROCEDURES_DEFRETURN_COMMENT = Blockly.Msg.PROCEDURES_DEFNORETURN_COMMENT;
Blockly.Msg.LISTS_GET_INDEX_HELPURL = Blockly.Msg.LISTS_INDEX_OF_HELPURL;